# Generated by Django 4.1.5 on 2023-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('ClothesName', models.CharField(default='Enter a name', max_length=200)),
                ('ClothesMaterial', models.CharField(default='Enter a material', max_length=200)),
                ('ClothesSize', models.CharField(default='Enter a size', max_length=200)),
                ('ClothesBrand', models.CharField(default='Enter a brand', max_length=200)),
                ('ClothesColor', models.CharField(default='Enter a color', max_length=200)),
                ('IDclothes', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
